# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
jobs:
  build:
    machine: 
      image: ubuntu-2004:202101-01

    steps:
      - checkout
      - run: ./configure
      - run: jam

workflows:
  build:
    jobs:
      - build:
          pre-steps:
            - run: sudo apt update
            - run: sudo apt install -y libxml2-dev libsdl2-dev libsdl2-gfx-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libphysfs-dev
